Backend/Plugins/LuaPlugin.cs, CHANGELOG.md, Frontend/MainWindow.Designer.cs, Frontend/MainWindow.cs, Shared/EventFactory.cs, Shared/EventHandler.cs, Shared/Events/UI/UIButtonTriggered.cs, Shared/Events/UI/UICommandCreateButton.cs, Shared/Events/UI/UICommandDeleteButton.cs, Shared/IEventFactory.cs, Slipstream.csproj
=> Lua-powered buttons

Backend/Plugins/ReceiverPlugin.cs, Backend/Plugins/TransmitterPlugin.cs, Backend/Services/EventSerdeService.cs, Backend/Services/TxrxService.cs
=> Use UTF-8 for ReceiverPlugin/TransmitterPlugin

Backend/Engine.cs, Backend/PluginManager.cs, Backend/Plugins/LuaManagerPlugin.cs, Backend/Plugins/LuaPlugin.cs, Backend/Services/LuaServiceLib/CoreMethodCollection.cs, Backend/Services/LuaServiceLib/LuaContext.cs, Backend/Services/LuaServiceLib/UIMethodCollection.cs, CHANGELOG.md, Frontend/MainWindow.cs, Shared/EventFactory.cs, Shared/EventHandler.cs, Shared/Events/Internal/InternalCommandDeduplicateEvents.cs, Shared/Events/Internal/InternalCommandReconfigure.cs, Shared/Events/LuaManager/LuaManagerCommandDeduplicateEvents.cs, Shared/IEventFactory.cs, Slipstream.csproj
While writing documentation, it became apparent to me, that there were some consistency problems, which have been fixed here
=> Consistency

Shared/Events/Audio/AudioCommandSendDevices.cs, Shared/Events/Audio/AudioCommandSetOutputDevice.cs, Shared/Events/Audio/AudioOutputDevice.cs
Fixing build errors by implementing the Uptime property and equality functions in the event classes.
=> Fixing build errors

Backend/Plugins/LuaManagerPlugin.cs
I broke it, when adding the timestamps
=> Fix event deduplication

Backend/Plugins/TwitchPlugin.cs, CHANGELOG.md, Shared/EventHandlers/Twitch.cs, Shared/Events/Twitch/TwitchGiftedSubscription.cs, Shared/Events/Twitch/TwitchRaided.cs, Shared/Events/Twitch/TwitchUserSubscribed.cs, Shared/Factories/ITwitchEventFactory.cs, Shared/Factories/TwitchEventFactory.cs, Slipstream.csproj, docs/events.md
I cant really test these, so be careful.
- Refactor: Sorted methods
- Adds support for Twitch subs/resubs event
- Adds support for twitch gifted subs
- Add support for twitch raid events
=> TwitchPlugin: Adds support for Sub/Resub, Gifted sub and Raids

Backend/Engine.cs, Backend/Plugins/AudioPlugin.cs, docs/init.lua.md
Sets the output device (index), as audio:set_output() would
Changed default init.lua file. Updated init.lua.md with default init.lua
fixes #54
=> Allow you to provide an "output" argument for AudioPlugin

Backend/Plugins/TwitchPlugin.cs, CHANGELOG.md, Shared/Events/Twitch/TwitchRaided.cs
Bonus: It will also keep pending messages while reconnecting
=> TwitchPlugin: Be throttle-aware

Components/Twitch/EventFactory/TwitchEventFactory.cs, Components/Twitch/Events/TwitchUserSubscribed.cs, Components/Twitch/ITwitchEventFactory.cs, Components/Twitch/Plugins/TwitchPlugin.cs, Components/Twitch/README.md
Judging by the events you provided me, @lawrab. The months value was zero. So this is an attempt in getting the correct values. And general improvements. Nothing interesting. Mostly fyi.
=> Hopefully fixed month values for user subscribed events

.circleci/config.yml, Slipstream.csproj, packages.config
I had to use quite a tricky approach to make sure the different versions of nuget packages restore correctly, this is not the correct way at this stage and I will need to research it further.
This seems to work for what we need at this point.
=> Add tests in CI

App.config
Fixing the KeraLua binding version in the app.config
=> Fixing KeraLua binding version

CHANGELOG.md, Components/IRacing/EventFactory/IRacingEventFactory.cs, Components/IRacing/EventHandler/IRacing.cs, Components/IRacing/Events/IRacingTowed.cs, Components/IRacing/IIRacingEventFactory.cs, Components/IRacing/Plugins/GameState/IState.cs, Components/IRacing/Plugins/GameState/State.cs, Components/IRacing/Plugins/GameState/StateFactory.cs, Components/IRacing/Plugins/Trackers/TowTracker.cs, Components/IRacing/Plugins/Trackers/Trackers.cs, Components/IRacing/README.md, Slipstream.UnitTests/Components/IRacing/Plugins/Trackers/TowTrackerTests.cs, Slipstream.UnitTests/TestData/TestState.cs, Slipstream.csproj
=> Detect iracing towing

App.config, Backend/Bootstrap/init.lua, Backend/Engine.cs, Components/AppilcationUpdate/ApplicationUpdate.cs, Components/AppilcationUpdate/EventFactory/ApplicationUpdateEventFactory.cs, Components/AppilcationUpdate/EventHandler/ApplicationUpdateEventHandler.cs, Components/AppilcationUpdate/Events/ApplicationUpdateCommandCheckLatestVersion.cs, Components/AppilcationUpdate/Events/ApplicationUpdateLatestVersionChanged.cs, Components/AppilcationUpdate/IApplicationUpdateEventFactory.cs, Components/AppilcationUpdate/Plugins/ApplicationUpdatePlugin.cs, Frontend/MainWindow.cs, Properties/AssemblyInfo.cs, Slipstream.csproj
- moved from UI to a Plugin
- Moved init.lua text to a resource instead of string in code
=> Refactoring Application Update implementation

LuaScripts/iracing_car.lua, LuaScripts/iracing_ir.lua, LuaScripts/iracing_prechecks.lua, LuaScripts/iracing_sof.lua, LuaScripts/iracing_track.lua, LuaScripts/lib/common.lua, Slipstream.csproj
- iracing_prechecks.lua: Remind to check car setup before qualify/race
- iracing_car.lua: adds "!car" command to twitch, showing current car
- iracing_track.lua: adds "!track" command to twitch, showing current track
- iracing_sof.lua: adds "!sof" command to twitch, showing current SoF
- iracing_ir.lua: adds "!ir" command to twitch, showing irating and safety rating
=> Adds various Lua samples

CHANGELOG.md, Properties/AssemblyInfo.cs
=> Publishing v0.6.0

Shared/Lua/BaseInstanceThread.cs
In case the thread was stopped (like if there is no handle function) and you would try to restart it, it would throw exception: "Thread is running or terminated; it cannot restart."
=> Fixes lua threads not begin restarted properly.

Components/Audio/Lua/AudioInstanceThread.cs
Changing how we initialise Audio devices and added completion event to track exceptions.
=> Implementing using for WaveOutEvent and init per call instead

App.config, CHANGELOG.md, Components/WinFormUI/Forms/MainWindow.cs, Properties/Settings.Designer.cs, Properties/Settings.settings
It could end up placing the Window off-screen, making it
hard to reach.
=> Bugfix: Dont persist UI location/size

Components/Lua/Lua/LuaInstanceThread.cs
=> Bugfix: generate_json() must not be static

Components/FileMonitor/Lua/FileMonitorInstanceThread.cs
Actually it will auto-create any directory you're
monitoring
=> Autocreate Scripts directory if missing

CHANGELOG.md, Components/JustGiving/EventFactory/JustGivingEventFactory.cs, Components/JustGiving/EventHandler/JustGiving.cs, Components/JustGiving/Events/JustGivingCommandSendDonations.cs, Components/JustGiving/Events/JustGivingDonation.cs, Components/JustGiving/Events/JustGivingInfo.cs, Components/JustGiving/IJustGivingEventFactory.cs, Components/JustGiving/Lua/IJustGivingInstanceThread.cs, Components/JustGiving/Lua/IJustGivingLuaReference.cs, Components/JustGiving/Lua/JustGivingInstanceThread.DonationFetcher.cs, Components/JustGiving/Lua/JustGivingInstanceThread.DonationMeta.cs, Components/JustGiving/Lua/JustGivingInstanceThread.DonationsResult.cs, Components/JustGiving/Lua/JustGivingInstanceThread.cs, Components/JustGiving/Lua/JustGivingLuaLibrary.cs, Components/JustGiving/Lua/JustGivingLuaReference.cs, Components/JustGiving/README.md, Program.cs, Samples/Common/Scripts/config.lua, Samples/JustGiving - Discord - Donation Announcer/Scripts/justgiving.lua, Slipstream.csproj
Allows you to monitor a justgiving page and e.g announce it to discord:
=> Justgiving component

Backend/Engine.cs, Backend/EventBus.cs, Backend/EventBusSubscription.cs, CHANGELOG.md, Components/Audio/Lua/AudioInstanceThread.AudioPlayerImpl.cs, Components/Audio/Lua/AudioInstanceThread.cs, Components/JustGiving/Lua/JustGivingInstanceThread.DonationFetcher.cs, Components/JustGiving/Lua/JustGivingInstanceThread.cs, Components/JustGiving/Lua/JustGivingLuaReference.cs, Components/Lua/Lua/InternalLuaReference.cs, Components/Lua/Lua/LuaInstanceThread.cs, Components/Twitch/Lua/TwitchLuaInstanceThread.cs, Program.cs, Shared/IEventBusSubscription.cs, Shared/Logger/SessionIdEnricher.cs, Shared/Logger/ThreadIdEnricher.cs, Shared/Lua/BaseInstanceThread.cs, Slipstream.csproj, SlipstreamConsoleSink.cs
Prototyping integration with [Seq](https://datalust.co/seq) (Free for personal use)
=> Send all logs to Seq. Console shows only Info or above

Components/WebSocket/Lua/WebSocketLuaInstanceThread.cs, Shared/Lua/BaseInstanceThread.cs
It should be a lot more robust now
=> Various fixes for websocket
