dennis/slipstream

- Backend/Plugins/FileMonitorPlugin.cs
- Backend/Plugins/FileTriggerPlugin.cs
- Backend/Plugins/IRacingPlugin.cs
- Backend/Plugins/LuaPlugin.cs
- CHANGELOG.md
- Shared/EventHandler.cs
- Shared/Events/Internal/FileMonitorScanCompleted.cs
- Shared/Events/Internal/Initialized.cs
- Slipstream.csproj
Plugins are registered and enabled all at once. But since Lua scripts are loaded by `FileTriggerPlugin`, they will first be loaded after we start. And since `IRacingPlugin` starts at the beginning, LuaScripts will miss events concerning Car Info, Weather Info, Track Info etc that `IRacingPlugin` initially published. 
To get around this, this PR adds a `Initialize` and `FileMonitorScanCompleted` event.s `Initialized` will be published once all Lua Script are registered, so `IRacingPlugin` should therefor just wait for this event, before publishing events.
- `FileMonitorPlugin`  (FMP) will emit `FileMonitorScanCompleted` once its done publishing `FileMonitorFileCreated` for existing files, found at startup
- `FileTriggerPlugin` (FTP) listens for events from FMP As long as no …
> IRacingPlugin  sends events before LuaScripts are ready

- Backend/EventBus.cs
- CHANGELOG.md
- Frontend/MainWindow.cs
- Shared/IEventBus.cs
UI needs it, as it might be started slightly later than the
plugins. So to show all events in the window, we'll do a
"replay" of all known events.
If 10.000 events is reached, we'll remove 1000 events at
a time.
> Store upto 10.000 events that we can replay if needed

- Backend/Services/LuaServiceLib/CoreMethodCollection.cs
- CHANGELOG.md
This now works:
function setup_random ()
local delay = math.random(0,9);
ui:print("setup_random delay = " .. delay)
core:wait("random-wait", function()
action(delay)
setup_random()
end, delay)
end
setup_random()
> Lua: core:wait('name', .. ) can now redefine itself

- Backend/PluginManager.cs
- Backend/Plugins/AudioPlugin.cs
- Backend/Services/LuaServiceLib/AudioMethodCollection.cs
- CHANGELOG.md
- Shared/EventHandlers/Audio.cs
- Shared/Events/Audio/AudioCommandPlay.cs
- Shared/Events/Audio/AudioCommandSay.cs
- Shared/Events/Audio/AudioCommandSendDevices.cs
- Shared/Events/Audio/AudioCommandSetOutputDevice.cs
- Shared/Events/Audio/AudioOutputDevice.cs
- Shared/Factories/AudioEventFactory.cs
- Shared/Factories/IAudioEventFactory.cs
- Slipstream.csproj
- docs/events.md
- docs/lua.md
Solves https://github.com/dennis/slipstream/issues/34
***Example***
Change *init-0.4.0*
```
register_plugin("AudioPlugin:Default", "AudioPlugin")
register_plugin("AudioPlugin:Other", "AudioPlugin")
```
*scripts/audio.lua*
```
audio:send_devices("AudioPlugin:Default") -- you will receive AudioOutputDevice events here
audio:set_output("AudioPlugin:Other", 2) -- "2" is a device reported by the above command
audio:say("AudioPlugin:Other", "Hello", 0.3)
audio:play("AudioPlugin:Default", "aww-sound-effect.mp3", 0.3)
```
Note: This breaks all `say` and `play`, as there now is a 3rd argument, that decides which plugin to use
> Audio select device

- Backend/EventBusSubscription.cs
- Backend/IPlugin.cs
- Backend/PluginManager.cs
- Backend/PluginWorker.cs
- Backend/Plugins/AudioPlugin.cs
- Backend/Plugins/BasePlugin.cs
- Backend/Plugins/FileMonitorPlugin.cs
- Backend/Plugins/IRacingPlugin.cs
- Backend/Plugins/LuaManagerPlugin.cs
- Backend/Plugins/LuaPlugin.cs
- Backend/Plugins/PlaybackPlugin.cs
- Backend/Plugins/ReceiverPlugin.cs
- Backend/Plugins/TransmitterPlugin.cs
- Backend/Plugins/TwitchPlugin.cs
- Backend/Worker.cs
- Slipstream.csproj
Instead of having a PluginWorker that runs 1 or more plugins, then
just have one plugin per PluginWorker. This will give overhead in
terms of some plugins doesn't do much, but it simplifies code and
Lua scripts doesn't need to share same thread
> Simplify plugin threads

- CHANGELOG.md
- Components/IRacing/EventFactory/IRacingEventFactory.cs
- Components/IRacing/EventHandler/IRacing.cs
- Components/IRacing/Events/IRacingTrackPosition.cs
- Components/IRacing/IIRacingEventFactory.cs
- Components/IRacing/Plugins/GameState/Car.cs
- Components/IRacing/Plugins/GameState/StateFactory.cs
- Components/IRacing/Plugins/Trackers/TrackPositionTracker.cs
- Components/IRacing/Plugins/Trackers/Trackers.cs
- Components/IRacing/README.md
- Slipstream.UnitTests/Components/IRacing/Plugins/Trackers/TrackPositionTrackerTests.cs
- Slipstream.UnitTests/TestData/GameStateBuilder.cs
- Slipstream.csproj
IRacingTrackPosition is published on every change - when a car gets
overtaken or overtakes anohter car
- It is only tested with road races, so currently it ignores anything else (see https://github.com/dennis/slipstream/blob/iracing-position-tracking/Components/IRacing/Plugins/Trackers/TrackPositionTracker.cs#L104-L108)
- Code is untested
> IRacing: Adds event for realtime position tracking

- Components/Discord/Plugins/DiscordPlugin.cs
AutoFac were expecting a "id", not "pluginId", so it would fail hard
> Make DiscordPlugin usable again

- Components/AppilcationUpdate/Lua/ApplicationUpdateInstanceThread.cs
- Components/AppilcationUpdate/Lua/ApplicationUpdateLuaLibrary.cs
- Components/AppilcationUpdate/Lua/ApplicationUpdateReference.cs
- Slipstream.csproj
- packages.config
It seems that Squirrel.Windows is dying. There have been an
vulnerbility[0] for in one of the dependencies, discovered on september
12th, 2019, that can be fixed by merely releasing a new version with
updated dependency. It's a trivial task, yet it wasn't done.
Also it seems that there was an attempt[1], but that didn't really find
new maintainers. electron consider the project as not maintained[2]
0: https://github.com/advisories/GHSA-fxh6-w476-hgr4
1: https://github.com/Squirrel/Squirrel.Windows/issues/1470
2: https://github.com/electron/electron/issues/17722
> Reimplement application update using AutoUpdaterDotNET

- Components/WinFormUI/Lua/WinFormUIInstanceThread.cs
UI sometimes throws this exception:
Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
> UI can crash because of missing STAThreadAttribute

- Shared/Lua/BaseInstanceThread.cs
If a lua script stops for some reason, and we restart it, it would
immediately stop again, as the "Stopping" flag wasn't reset to false.
> BUGFIX: Dont stop restarted instances immediately

- Components/WinFormUI/Forms/MainWindow.cs
We're not adding dependency on this component,
so only distributing shutdowns to known listener
does not make sense. Everybody needs to shut down.
> Broadcast Shutdown event to all listeners

- Components/Twitch/Lua/TwitchLuaInstanceThread.cs
- Shared/Lua/BaseInstanceThread.cs
It would try to reconnect, as it reacted to the
OnDisconect() event and would always try to
reconnect, which it sometimes did, before
slipstream was finish shutting down.
Now it is aware of Shutdown event and will
only reconnect if we're not shutting down.
> Fixes twich shutdown

- Components/IRacing/Trackers/Trackers.cs
If IRacing isn't running, but you send a:
IRacingCommandSendCarInfo / SendTrackInfo / SendTrackInfo / WeatherInfo / SessionState / SendRaceFlags event, it would cause IRacingThead
to crash.
> Bugfix: IRacingThread crash.

- Components/IRacing/Trackers/PitUsageTracker.cs
In team events, when changing driver, you would get two PitEntry events
> Bugfix: Duplicated PitEntry

- Components/WebWidget/HttpServer.cs
- Components/WebWidget/IHttpServerApi.cs
- Components/WebWidget/IWebWidgetInstances.cs
- Components/WebWidget/Lua/WebWidgetInstanceThread.cs
- Components/WebWidget/WebWidgetInstances.cs
- Shared/Lua/BaseInstanceThread.cs
- Shared/Lua/BaseLuaLibrary.cs
- Shared/Lua/ILuaInstanceThread.cs
- Shared/Lua/NoopInstanceThread.cs
If an instance would have no dependencies and decides
to shut down, Slipstream would never be able to start it
again.
> Fix instances would not restart even if requested

- CHANGELOG.md
- Components/AppilcationUpdate/EventFactory/ApplicationUpdateEventFactory.cs
- Components/Audio/EventFactory/AudioEventFactory.cs
- Components/Discord/EventFactory/DiscordEventFactory.cs
- Components/FileMonitor/EventFactory/FileMonitorEventFactory.cs
- Components/IRacing/EventFactory/IRacingEventFactory.cs
- Components/Internal/EventFactory/InternalEventFactory.cs
- Components/Lua/EventFactory/LuaEventFactory.cs
- Components/Playback/EventFactory/PlaybackEventFactory.cs
- Components/Twitch/EventFactory/TwitchEventFactory.cs
- Components/WebWidget/EventFactory/WebWidgetEventFactory.cs
- Components/WinFormUI/EventFactory/WinFormUIEventFactory.cs
- Shared/EventEnvelope.cs
- Shared/IEventEnvelope.cs
The timestamp `uptime` is updated when you publish an event. As we only
create a new envelope everytime we changed/add recipients, multiple
events would share the same envelope. This isn't a problem, unless you
consider the envelope also contains the timestamp. So suddenly all
events sharing the same envelope would have the timestamp of the last
event using that envelope.
When viewing the events they would seem out of order.
> Bugfix: Events shared timestamp

- CHANGELOG.md
- Components/WinFormUI/Forms/MainWindow.cs
- Components/WinFormUI/Lua/WinFormUIInstanceThread.cs
This would happen while it was creating the UI. To get around this, the
subscription is created before initializing UI, so at least the events
are queued until it's ready to process them
> WinFormUI wouldn't always pick up creation events

- CHANGELOG.md
- Components/WinFormUI/Lua/WinFormUIInstanceThread.cs
- Shared/EventHandlerController.cs
- Shared/IEventHandlerController.cs
- Shared/Lua/BaseInstanceThread.cs
Reloading script triggered a problem, that this hopefully will fix: When
a lua script is reloaded its removed + loaded. When removing the script
it sends out InternalDependencyRemoved and if one or more instance isn't
used it will shut down. However if the instance didnt process that event
yet (so still running, but soon will stop) and the new script checks if
the instance is available (which it is) and a moment later the instance
would process the event and shut down, leaving the script with a missing
instance - aka it would be broken in some way.
With this change it will wait for a bit (at least 10 seconds), before
shutting down, so when reloading there is plenty of time to load the
script again without instances shutting down.
> Dont terminate inactive instances immediately

- CHANGELOG.md
- Components/Audio/Lua/AudioInstanceThread.AudioPlayerImpl.cs
- Components/WinFormUI/Forms/MainWindow.cs
Inside the thread, we were blocking until it would would finish. Which
never happens, because the thread were blocking until it would would
finish.  Which never happens ..
> Bugfix: Let AudioPlayer thread shut fully down

- Components/Lua/Lua/LuaInstanceThread.cs
Would error with:
errored while invoking handle(): Can't pass instance to static method generate_json
Did a refactoring that suggested adding 'static' to the method signature
> bugfix: Broekn generate_json() lua function
